spring.application.name=pdf-mentor-backend
spring.ai.google.gemini.api-key=AIzaSyDrMybtkrg3cPElkvDsbM3JC67yZYOA7oY
spring.ai.google.gemini.chat.options.model=gemini-1.5-flash
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
server.port=8080
